spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          format_sql: true